apiVersion: batch/v1
kind: Job
metadata:
  name: python-app-job
spec:
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: postgres
        image: tomattoid/postgres:tagname
      restartPolicy: Never
