apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/models"
