apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler-cronjob
  labels:
    app: crawler-app
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          name: crawler-pod
          labels:
            app: crawler-app
        spec:
          containers:
            - name: crawler-container
              image: tomattoid/otomoto-crawler:latest
              imagePullPolicy: Always
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres-root-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres-root-user
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres-db
                - name: POSTGRES_SERVICE
                  value: postgres-service
          restartPolicy: Never
