apiVersion: batch/v1
kind: Job
metadata:
  name: retrain-job
  labels:
    app: retrain-app
spec:
  template:
    metadata:
      name: retrain-pod
      labels:
        app: retrain-app
    spec:
      containers:
        - name: retrain-container
          image: tomattoid/retrain-app:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: POSTGRES_SERVICE
              value: postgres-service
          volumeMounts:
            - name: model-volume
              mountPath: /mnt/data
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-pvc
      restartPolicy: Never
